function lg -d "grep me from a line!"
    command lg $argv
end

complete -c lg -s A -l after-context -d "Print NUM lines of trailing context" -x
complete -c lg -s a -l text -d "Process binary file as text"
complete -c lg -s B -l before-context -d "Print NUM lines of leading context" -x
complete -c lg -s C -l context -d "Print NUM lines of context" -x
complete -c lg -s b -l byte-offset -d "Print byte offset of matches"
complete -c lg -l binary-files -d "Assume data type for binary files" -x -a "binary\tBinary\ format text\tText\ format"
complete -c lg -l colour -f -d "Colour output" -a "never always auto"
complete -c lg -l color -f -d "Color output" -a "never always auto"
complete -c lg -s c -l count -d "Only print number of matches"
complete -c lg -s D -l devices -x -a "read skip" -d "Action for devices"
complete -c lg -s d -l directories -x -a "read skip recurse" -d "Action for directories"
complete -c lg -s E -l extended-regexp -d "Pattern is extended regexp"
complete -xc lg -s e -l regexp -d "Specify a pattern"
complete -rc lg -l exclude-from -d "Read pattern list from file. Skip files whose base name matches list"
complete -rc lg -l exclude-dir -d "Exclude matching directories from recursive searches"
complete -c lg -s F -l fixed-strings -d "Pattern is a fixed string"
complete -rc lg -s f -l file -d "Use patterns from a file"
complete -c lg -s G -l basic-regexp -d "Pattern is basic regex"
complete -c lg -s H -l with-filename -d "Print filename"
complete -c lg -s h -l no-filename -d "Suppress printing filename"
complete -c lg -l help -d "Display help and exit"
complete -c lg -s I -d "Skip binary files"
complete -c lg -s i -l ignore-case -d "Ignore case"
complete -c lg -s L -l files-without-match -d "Print name of files without matches"
complete -c lg -s l -l files-with-matches -d "Print name of files with matches"
complete -c lg -s m -l max-count -d "Stop reading after NUM matches"
complete -c lg -l mmap -d "Use the mmap system call to read input"
complete -c lg -s n -l line-number -d "Print line number"
complete -c lg -s o -l only-matching -d "Show only matching part"
complete -c lg -l label -d "Rename stdin" -x
complete -c lg -l line-buffered -d "Use line buffering"
complete -c lg -s P -l perl-regexp -d "Pattern is a Perl regexp (PCRE) string"
complete -c lg -s q -l quiet -d "Do not write anything"
complete -c lg -l silent -d "Do not write anything"
complete -c lg -s R -l dereference-recursive -d "Recursively read files under each directory, following symlinks"
complete -c lg -s r -l recursive -d "Recursively read files under each directory"
complete -c lg -l include -d "Search only files matching PATTERN" -r
complete -c lg -l exclude -d "Skip files matching PATTERN" -r
complete -c lg -s s -l no-messages -d "Suppress error messages"
complete -c lg -s T -l initial-tab -d "Ensure first character of actual line content lies on a tab stop"
complete -c lg -s U -l binary -d "Treat files as binary"
complete -c lg -s u -l unix-byte-offsets -d "Report Unix-style byte offsets"
complete -c lg -s V -l version -d "Display version and exit"
complete -c lg -s v -l invert-match -d "Invert the sense of matching"
complete -c lg -s w -l word-regexp -d "Only whole matching words"
complete -c lg -s x -l line-regexp -d "Only whole matching lines"
complete -c lg -s z -l null-data -d "Treat input as a set of zero-terminated lines"
complete -c lg -s Z -l null -d "Output a zero byte after filename"
complete -c lg -l group-separator -x -d "Set a group separator"
complete -c lg -l no-group-separator -d "Use empty string as a group separator"
